device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files

#Predefining paths that can be used later
segmented_minikinetics50_train: dataset/segmented_minikinetics50/segmented_minikinetics50_train.csv
segmented_minikinetics50_val: dataset/segmented_minikinetics50/segmented_minikinetics50_validation.csv
original_minikinetics50_train: dataset/mini50_clean_train.csv
original_minikinetics50_val: dataset/HAT_minikinetics50_validation.csv

batch_size: 20
learning_rate: 0.001
num_epochs: 300

last_epoch_saved: None # Last epoch saved, used for resuming training
num_dataloader_workers: 20

model_type: slow_r50 #options: ['stack_concat', 'sum_concat', 'slow_r50']

dataset_type_train: original_minikinetics50_train
#options: ['segmented_minikinetics50_train', 'original_minikinetics50_train', 'dual_original_and_segmented_minikinetics50_train']

dataset_type_val: original_minikinetics50_val
#options: ['segmented_minikinetics50_val', 'original_minikinetics50_val', 'dual_original_and_segmented_minikinetics50_val']

#TODO: change this name
wandb_name: Training baseline Slow on Original MiniKinetics50 (w/ Adam optimizer and LR=0.001)
weights_dir: slowfast_minikinetics50/slow_baseline_adam_001  # Directory to save model weights

