device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files
batch_size: 60 
learning_rate: 0.01
num_epochs: 200
train_csv: dataset/mini50_clean_train.csv
val_csv: dataset/mini50_clean_validation.csv
weights_dir: slowfast_minikinetics50  # Directory to save model weights
last epoch saved: None # Last epoch saved, used for resuming training
num_dataloader_workers: 36
wandb_name: miniKinetics
