device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files
batch_size: 20
learning_rate: 0.01
num_epochs: 300
train_csv: dataset/mini50_clean_train.csv
val_csv: dataset/HAT_minikinetics50_validation.csv
weights_dir: slowfast_minikinetics50/slow_pretrain  # Directory to save model weights
last_epoch_saved: None # Last epoch saved, used for resuming training
num_dataloader_workers: 20
#TODO: change it

wandb_name: Pre-training Slow on MiniKinetics50

