device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files

mimetics_test: dataset/mimetics/mimetics_mcq_all_fields.csv
hat_actionswap_test: dataset/action_swap/action_swap_mcq_all_fields.csv

batch_size: 20
learning_rate: 0.001
num_epochs: 300
last_epoch_saved: 300 # Last epoch saved, used for resuming training
num_dataloader_workers: 20

model_type: slow_r50 #options: ['stack_concat', 'sum_concat', 'slow_r50', 'slow_humanseg', 
# 'weighted_focus1', 'weighted_focus2']

dataset_type_train: original_minikinetics50_train
#options (mix means that we mix the minikinetics with the places365 action-action swap)
# segmented_minikinetics50_train
# original_minikinetics50_train
# dual_original_and_segmented_minikinetics50_train
# original_and_binmask_minikinetics50_train
# original_mix_train
# segmented_mix_train
# dual_original_and_segmented_mix_train
# dual_original_and_binmask_mix_train

dataset_type_val: original_minikinetics50_val
#options:
# segmented_minikinetics50_val
# original_minikinetics50_val
# dual_original_and_segmented_minikinetics50_val
# original_and_binmask_minikinetics50_val
# original_mix_val
# segmented_mix_val
# dual_original_and_segmented_mix_val
# dual_original_and_binmask_mix_val


#TODO: change this name
wandb_name: Baseline Slow
weights_dir: new_weights_dir/slow_baseline  # Directory to save model weights
