device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files
batch_size: 60
learning_rate: 0.01
num_epochs: 300
train_csv: dataset/segmented_minikinetics50/segmented_minikinetics50_train.csv
val_csv: dataset/segmented_minikinetics50/segmented_minikinetics50_validation.csv
weights_dir: slowfast_minikinetics50/slow_humanseg  # Directory to save model weights
last_epoch_saved: None # Last epoch saved, used for resuming training
num_dataloader_workers: 20
wandb_name: Training (raw) Slow on Segmented MiniKinetics50

