device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files
batch_size: 20
learning_rate: 0.01
num_epochs: 300
train_csv: dataset/segmented_minikinetics50/segmented_minikinetics50_train.csv
val_csv: dataset/segmented_minikinetics50/segmented_minikinetics50_validation.csv
weights_dir: slowfast_minikinetics50/sum_concat  # Directory to save model weights
last_epoch_saved: None # Last epoch saved, used for resuming training
num_dataloader_workers: 20

model_type: sum_concat

wandb_name: Training my custom sum-concat model on MiniKinetics50 seg & original

