device: cuda  # Will need to be dynamically determined in code
metadata_dir: /n/fs/visualai-scr/temp_LLP/ellie/slowfast_kinetics  # Directory containing curated CSV files

#Predefining paths that can be used later
segmented_minikinetics50_train: dataset/minikinetics50/minikinetics50_train_all.csv
segmented_minikinetics50_val: dataset/minikinetics50/minikinetics50_validation_all.csv

batch_size: 20
learning_rate: 0.001
num_epochs: 300

last_epoch_saved: None # Last epoch saved, used for resuming training
num_dataloader_workers: 20

model_type: weighted_focus2 #options: ['stack_concat', 'sum_concat', 'slow_r50', 'weighted_focus']

dataset_type_train: original_and_binmask_minikinetics50_train
#options: ['segmented_minikinetics50_train', 'original_minikinetics50_train', 'dual_original_and_segmented_minikinetics50_train',
# 'original_and_binmask_minikinetics50_train']

dataset_type_val: original_and_binmask_minikinetics50_val
#options: ['segmented_minikinetics50_val', 'original_minikinetics50_val', 'dual_original_and_segmented_minikinetics50_val',
# 'original_and_binmask_minikinetics50_val']

#TODO: change this name
wandb_name: Weighted-Focus2 (ADAM, LR 0.001)
weights_dir: slowfast_minikinetics50/weighted_focus2__adam_lr_001_new  # Directory to save model weights